[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
crabswap_router = "8Vp1dKYRVNxYNCmAdjhnpXyRKuPB8cfjRgoazzcfL4p4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/new_wallet.json"

[workspace]
members = ["programs/*"]

[scripts]
test = "yarn run ts-mocha -t 1000000 tests/**/*.ts"
